"use strict";
if (!HAS_FUNCTION_BIND) require("./function/function_bind");
if (!IS_ARRAY_SPLICE_WORKS_AS_EXPECTED) require("./array/array_splice");
if (!IS_ARRAY_UNSHIFT_WORKS_AS_EXPECTED) require("./array/array_unshift");
if (!HAS_ARRAY_IS_ARRAY) require("./array/isArray");
if (!HAS_ARRAY_FOREACH) require("./array/array_forEach");
if (!HAS_ARRAY_MAP) require("./array/array_map");
if (!HAS_ARRAY_FILTER) require("./array/array_filter");
if (!HAS_ARRAY_EVERY) require("./array/array_every");
if (!HAS_ARRAY_SOME) require("./array/array_some");
if (!HAS_ARRAY_REDUCE) require("./array/array_reduce");
if (!HAS_ARRAY_REDUCE_RIGHT) require("./array/array_reduceRight");
if (!HAS_ARRAY_INDEX_OF) require("./array/array_indexOf");
if (!HAS_ARRAY_LAST_INDEX_OF) require("./array/array_lastIndexOf");
if (!HAS_OBJECT_KEYS) require("./object/keys");
if (!HAS_NUMBER_TO_FIXED) require("./number/number_toFixed");
if (!IS_STRING_SPLIT_WORKS_AS_EXPECTED) require("./string/string_split");
